# Header
# the school-web part should not be necessary but is
menu:
  Home: /school-web/
  Gallery: /school-web/Gallery
#  archives: /archives
rss: /school-web/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
